name: testsuite

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
  pull_request:

env:
  PERL_SKIP_TTY_TEST: 1
  CONTINUOUS_INTEGRATION: 1

permissions:
  contents: read # to fetch code

jobs:
  #  ___           _         ___       __                    _   _
  # / __|_ __  ___| |_____  |_ _|_ _  / _|___ _ _ _ __  __ _| |_(_)___ _ _  ___
  # \__ \ '  \/ _ \ / / -_)  | || ' \|  _/ _ \ '_| '  \/ _` |  _| / _ \ ' \(_-<
  # |___/_|_|_\___/_\_\___| |___|_||_|_| \___/_| |_|_|_\__,_|\__|_\___/_||_/__/

  #     _    ____    _    _   _
  #    / \  / ___|  / \  | \ | |
  #   / _ \ \___ \ / _ \ |  \| |
  #  / ___ \ ___) / ___ \| |\  |
  # /_/   \_\____/_/   \_\_| \_|

  # Life is pain, highness. Anyone who says differently is selling something.

  ASAN:
    name: "ASAN"
    runs-on: ubuntu-latest
    timeout-minutes: 120

    strategy:
      matrix:
        # -DPURIFY disables arenas and mallocs everything individually. With
        # ASAN or similar it's the real torture test. However, we also need to
        # test that the arena code doesn't have any goofs.
        CONFIGURE_ARGS:
          - "-Accflags=-DPURIFY"
          - "-DDEBUGGING"
          - "-Dusethreads"

    steps:
      - name: Install System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdbm-dev libdb-dev
      - uses: actions/checkout@v4
      - name: git cfg
        run: |
          git config diff.renameLimit 999999
      - name: Configure
        run: |
          ./Configure -des -Dusedevel -Dcc="clang -fsanitize=address" -Dld="clang -fsanitize=address" ${{ matrix.CONFIGURE_ARGS }} -Dprefix="$HOME/perl-blead"
      - name: Build
        run: |
          PERL_DESTRUCT_LEVEL=2 make -j2 test_prep
      - name: Show Config
        run: |
          PERL_DESTRUCT_LEVEL=2  ./perl -Ilib -V
          PERL_DESTRUCT_LEVEL=2  ./perl -Ilib -e 'use Config; print Config::config_sh'
      - name: Run Tests
        # LeakSanitizer is disabled because it randomly crashes, see [gh #19189]
        run: |
          PERL_DESTRUCT_LEVEL=2 TEST_JOBS=2 ./perl t/harness
